name: Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install jupyter-book ghp-import

      - name: Build the Jupyter Book
        run: jupyter-book build my-jupyter-book/

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f my-jupyter-book/_build/html
